export enum Errors {
    WRONG_CODE = "WRONG_CODE",
    PASSWORD_MISMATCH = "PASSWORD_MISMATCH",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    WRONG_PASSWORD = "WRONG_PASSWORD",
    EMAIL_EXISTS = "EMAIL_EXISTS",
    NO_TOKEN = "NO_TOKEN",
    INVALID_TOKEN = "INVALID_TOKEN"
}